// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAJJebMuHj2Q4Q6HX8e7C17vsgEiOoNte4',
//     appId: '1:277002066861:web:56b11da551e6899bd41f24',
//     messagingSenderId: '277002066861',
//     projectId: 'campus-talk-23a7a',
//     authDomain: 'campus-talk-23a7a.firebaseapp.com',
//     storageBucket: 'campus-talk-23a7a.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBcO6NszIV7OLHvog38fCmpE3mAI2VDPEU',
//     appId: '1:277002066861:android:321065220eefe8d0d41f24',
//     messagingSenderId: '277002066861',
//     projectId: 'campus-talk-23a7a',
//     storageBucket: 'campus-talk-23a7a.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDYs4oinID_SXrZuBFivkWTiZrH9o_j9YU',
//     appId: '1:277002066861:ios:da046d6e43aa936bd41f24',
//     messagingSenderId: '277002066861',
//     projectId: 'campus-talk-23a7a',
//     storageBucket: 'campus-talk-23a7a.appspot.com',
//     iosClientId: '277002066861-tkp5adcusbvbjm0heiuh8kqfit7shhg2.apps.googleusercontent.com',
//     iosBundleId: 'com.example.usersms',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDYs4oinID_SXrZuBFivkWTiZrH9o_j9YU',
//     appId: '1:277002066861:ios:7615a81343d335a3d41f24',
//     messagingSenderId: '277002066861',
//     projectId: 'campus-talk-23a7a',
//     storageBucket: 'campus-talk-23a7a.appspot.com',
//     iosClientId: '277002066861-n4sk2etkjmslddq31vg541a8v69a68vr.apps.googleusercontent.com',
//     iosBundleId: 'com.example.usersms.RunnerTests',
//   );
// }
